/**
 * Wingman lines library — shared data foundation (design.md §8, library.md).
 *
 * The Library page (/library) renders ~63 filterable lines with copy +
 * favorites (localStorage `wm:favs`). Every line carries: text, context tags,
 * a stage tag, a tone, and the research principle it descends from.
 *
 * Ethical spine: confident, specific, playful, respectful. No negging, no
 * pressure. Fading interest gets one revival swing, then a graceful exit.
 */

import type { ChatContext, ConversationStage, Tone } from './engine';

export type LineCategory = 'opener' | 'banter' | 'date-ask' | 'exit' | 'revival';

export const CATEGORY_LABELS: Record<LineCategory, string> = {
  opener: 'OPENERS',
  banter: 'BANTER',
  'date-ask': 'DATE ASKS',
  exit: 'GRACEFUL EXITS',
  revival: 'REVIVALS',
};

/** Short mono chip label for each chat context (library.md §3 card top row). */
export const CONTEXT_CHIP_LABELS: Record<ChatContext, string> = {
  tinder: 'TINDER',
  bumble: 'BUMBLE',
  hinge: 'HINGE',
  texting: 'TEXT',
  imessage: 'TEXT',
  instagram: 'IG',
  other: 'ANY',
};

/** Filter-bar context groups (library.md §2): multi-select toggle chips. */
export type ContextGroup = 'apps' | 'texting' | 'instagram';

export const CONTEXT_GROUPS: Record<ContextGroup, { label: string; contexts: ChatContext[] }> = {
  apps: { label: 'APPS', contexts: ['tinder', 'bumble', 'hinge'] },
  texting: { label: 'TEXTING', contexts: ['texting', 'imessage'] },
  instagram: { label: 'INSTAGRAM', contexts: ['instagram'] },
};

export interface LibraryLine {
  id: string;
  category: LineCategory;
  tone: Tone;
  stage: ConversationStage;
  text: string;
  /** Mono chip — the principle the line demonstrates. */
  principle: string;
  /** Published source behind the principle, when one exists. */
  citation?: string;
  contexts: ChatContext[];
  /** One line on why it works. */
  why: string;
}

const OPENERS: LibraryLine[] = [
  /* ------------------------------ OPENERS (30) ----------------------------- */
  {
    id: 'op-01',
    category: 'opener',
    tone: 'charming',
    stage: 'opener',
    text: 'Okay, [specific thing in her bio] — I need the story. Nobody puts that there by accident.',
    principle: 'SPECIFICITY',
    citation: 'Speed-dating follow-up research',
    contexts: ['tinder', 'hinge'],
    why: 'A specific observation outperforms every generic opener; it proves attention.',
  },
  {
    id: 'op-02',
    category: 'opener',
    tone: 'playful',
    stage: 'opener',
    text: 'Two truths and a lie. Loser plans the first date. I’ll go first: I once DJ’d a wedding by accident, I hate coffee, and I’ve met a sloth.',
    principle: 'PLAYFULNESS',
    citation: 'Hall, 2015',
    contexts: ['tinder', 'hinge'],
    why: 'A game gives her an easy reply hook — and shared humor predicts interest.',
  },
  {
    id: 'op-03',
    category: 'opener',
    tone: 'charming',
    stage: 'opener',
    text: 'Your prompt about [her prompt answer] is doing a lot of work here. Elaborate.',
    principle: 'RESPONSIVENESS',
    citation: 'Birnbaum & Reis',
    contexts: ['hinge'],
    why: 'Inviting her to expand signals you actually want to listen, not perform.',
  },
  {
    id: 'op-04',
    category: 'opener',
    tone: 'direct',
    stage: 'opener',
    text: 'Skipping the small talk: what’s the best meal you’ve had this year, and why do I suspect it was [guess tied to her photos]?',
    principle: 'SPECIFICITY',
    contexts: ['tinder', 'hinge'],
    why: 'Direct plus specific reads as confident, not lazy.',
  },
  {
    id: 'op-05',
    category: 'opener',
    tone: 'playful',
    stage: 'opener',
    text: 'Your [photo or prompt] raised a question only you can answer: [playful specific question]. Take your time — this matters.',
    principle: 'CURIOSITY',
    contexts: ['tinder', 'hinge'],
    why: 'Mock gravity around a tiny question is charming and easy to answer.',
  },
  {
    id: 'op-06',
    category: 'opener',
    tone: 'charming',
    stage: 'opener',
    text: 'I was going to lead with something smooth, but honestly your [specific detail] broke my concentration.',
    principle: 'KNOWN LIKING',
    contexts: ['hinge'],
    why: 'We like people who like us — honest interest beats practiced cool.',
  },
  {
    id: 'op-07',
    category: 'opener',
    tone: 'charming',
    stage: 'opener',
    text: '[Book, show, or hobby in her profile]? Excellent taste. The algorithm finally earned its keep.',
    principle: 'SIMILARITY',
    citation: 'Byrne, 1971',
    contexts: ['tinder', 'hinge'],
    why: 'Perceived similarity is one of the strongest, oldest predictors of attraction.',
  },
  {
    id: 'op-08',
    category: 'opener',
    tone: 'playful',
    stage: 'opener',
    text: 'Important compatibility test: [light either/or from her bio — mountains or ocean]? There’s a wrong answer and I hope you pick it so we can debate.',
    principle: 'PLAYFULNESS',
    citation: 'Hall, 2015',
    contexts: ['tinder', 'hinge'],
    why: 'A low-stakes debate invites banter, and banter is the whole point.',
  },
  {
    id: 'op-09',
    category: 'opener',
    tone: 'direct',
    stage: 'opener',
    text: 'You seem like you have good stories. Give me the one you tell at dinner parties.',
    principle: 'SELF-DISCLOSURE',
    citation: 'Aron et al., 1997',
    contexts: ['tinder', 'hinge'],
    why: 'Inviting a story opens the reciprocal-disclosure loop that builds closeness.',
  },
  {
    id: 'op-10',
    category: 'opener',
    tone: 'charming',
    stage: 'opener',
    text: 'The [specific detail] photo deserves context, and I am formally requesting it.',
    principle: 'SPECIFICITY',
    contexts: ['tinder'],
    why: 'Playful formality plus a specific target is memorable and pressure-free.',
  },
  {
    id: 'op-11',
    category: 'opener',
    tone: 'charming',
    stage: 'opener',
    text: 'It’s [your name] from [app] — the one who [callback to your chat]. Promised myself I’d text before this became a “whatever happened to” story.',
    principle: 'MOMENTUM',
    contexts: ['imessage'],
    why: 'Moving off the app quickly keeps a warm thread from going cold.',
  },
  {
    id: 'op-12',
    category: 'opener',
    tone: 'playful',
    stage: 'opener',
    text: 'Officially graduating you from dating app to actual phone. The ceremony was brief but moving.',
    principle: 'PLAYFULNESS',
    citation: 'Hall, 2015',
    contexts: ['imessage'],
    why: 'Marks the milestone with humor instead of an awkward “hey, it’s me.”',
  },
  {
    id: 'op-13',
    category: 'opener',
    tone: 'direct',
    stage: 'opener',
    text: 'Saving you a scroll: it’s me. Still thinking about your take on [topic from the chat].',
    principle: 'THE CALLBACK',
    contexts: ['imessage'],
    why: 'Recall is the proof of attention — the oldest seduction on record.',
  },
  {
    id: 'op-14',
    category: 'opener',
    tone: 'charming',
    stage: 'opener',
    text: '[Genuine reaction to her story] — wait, how did you end up there?',
    principle: 'RESPONSIVENESS',
    citation: 'Birnbaum & Reis',
    contexts: ['instagram'],
    why: 'Reacting to what she chose to share is attention without agenda.',
  },
  {
    id: 'op-15',
    category: 'opener',
    tone: 'playful',
    stage: 'opener',
    text: 'Posting [her food story] without an invitation to the rest of us is a bold legal strategy. What is it and where?',
    principle: 'PLAYFULNESS',
    citation: 'Hall, 2015',
    contexts: ['instagram'],
    why: 'Teasing the situation, never her — humor with a built-in question.',
  },
  {
    id: 'op-16',
    category: 'opener',
    tone: 'charming',
    stage: 'opener',
    text: 'Your [hobby] posts are honestly the best thing on my feed right now. How long have you been into it?',
    principle: 'KNOWN LIKING',
    contexts: ['instagram'],
    why: 'A sincere compliment about her passion, followed by a real question.',
  },
  {
    id: 'op-17',
    category: 'opener',
    tone: 'direct',
    stage: 'opener',
    text: 'We’ve liked each other’s stories for months. Hi, I’m [name] — figured I’d say it properly.',
    principle: 'MOMENTUM',
    contexts: ['instagram'],
    why: 'Names the mutual signals honestly and converts them into a conversation.',
  },
  {
    id: 'op-18',
    category: 'opener',
    tone: 'playful',
    stage: 'opener',
    text: 'Okay, that view is unfair. Adding it to the list of places you’ve made me jealous of. Worth the trip?',
    principle: 'PLAYFULNESS',
    citation: 'Hall, 2015',
    contexts: ['instagram'],
    why: 'Playful envy flatters the photo and hands her an easy verdict to give.',
  },
  {
    id: 'op-19',
    category: 'opener',
    tone: 'charming',
    stage: 'opener',
    text: 'You and I both listed [shared interest]. Statistically we’re obligated to at least discuss it.',
    principle: 'SIMILARITY',
    citation: 'Byrne, 1971',
    contexts: ['tinder', 'hinge'],
    why: 'Leads with common ground — similarity is the engine of early attraction.',
  },
  {
    id: 'op-20',
    category: 'opener',
    tone: 'playful',
    stage: 'opener',
    text: 'Full honesty: I swiped for the [dog / plant / pasta] in your photos. Staying for the bio.',
    principle: 'SPECIFICITY',
    contexts: ['tinder'],
    why: 'Self-deprecating honesty plus a genuine compliment on her words.',
  },
  {
    id: 'op-21',
    category: 'opener',
    tone: 'direct',
    stage: 'opener',
    text: 'No games: your profile was the most interesting thing I’ve seen today. What’s the story behind [specific detail]?',
    principle: 'KNOWN LIKING',
    contexts: ['tinder', 'hinge'],
    why: 'Expressed liking is reciprocated — directness with a question, not a demand.',
  },
  {
    id: 'op-22',
    category: 'opener',
    tone: 'playful',
    stage: 'opener',
    text: 'That answer about [her prompt] made me laugh out loud in a very quiet café. You owe me a reputation repair.',
    principle: 'PLAYFULNESS',
    citation: 'Hall, 2015',
    contexts: ['hinge'],
    why: 'Tells her she’s funny — the compliment everyone actually wants.',
  },
  {
    id: 'op-23',
    category: 'opener',
    tone: 'playful',
    stage: 'opener',
    text: 'You give off strong “plans the group trip” energy. Accurate?',
    principle: 'SPECIFICITY',
    contexts: ['tinder'],
    why: 'A light, positive read of her vibe invites her to confirm or correct.',
  },
  {
    id: 'op-24',
    category: 'opener',
    tone: 'charming',
    stage: 'opener',
    text: 'Real question, no pickup line: what’s something you’re looking forward to this month?',
    principle: 'RESPONSIVENESS',
    citation: 'Birnbaum & Reis',
    contexts: ['tinder', 'hinge'],
    why: 'Forward-looking questions surface enthusiasm — and enthusiasm is contagious.',
  },
  {
    id: 'op-25',
    category: 'opener',
    tone: 'direct',
    stage: 'opener',
    text: 'Your [interest] credentials are impressive. I’m [adjacent interest]. Seems like a conversation worth having.',
    principle: 'SIMILARITY',
    citation: 'Byrne, 1971',
    contexts: ['tinder', 'hinge'],
    why: 'Respectful confidence: names the overlap and proposes the conversation.',
  },
  {
    id: 'op-26',
    category: 'opener',
    tone: 'playful',
    stage: 'opener',
    text: 'On a scale of “mildly amusing” to “canceled plans for it,” how into [her hobby] are you?',
    principle: 'PLAYFULNESS',
    citation: 'Hall, 2015',
    contexts: ['tinder', 'hinge'],
    why: 'A scale question is effortless to answer and sets a playful register.',
  },
  {
    id: 'op-27',
    category: 'opener',
    tone: 'charming',
    stage: 'opener',
    text: 'Still thinking about what you said about [topic] the other night. You argue a good case. How’s your week looking?',
    principle: 'THE CALLBACK',
    contexts: ['imessage'],
    why: 'First text after meeting in person: recall plus a gentle, open question.',
  },
  {
    id: 'op-28',
    category: 'opener',
    tone: 'playful',
    stage: 'opener',
    text: 'Bet I can guess your most-used emoji from your bio alone. Give me one clue.',
    principle: 'CURIOSITY',
    contexts: ['tinder', 'hinge'],
    why: 'A tiny wager creates a curiosity gap she can close with one word.',
  },
  {
    id: 'op-29',
    category: 'opener',
    tone: 'charming',
    stage: 'opener',
    text: 'This might be bold for a first message, but your [specific post] deserved more than a like.',
    principle: 'KNOWN LIKING',
    contexts: ['instagram'],
    why: 'Acknowledges the boldness, then justifies it with genuine appreciation.',
  },
  {
    id: 'op-30',
    category: 'opener',
    tone: 'direct',
    stage: 'opener',
    text: 'Everyone probably asks about the [obvious thing]. I want to know about [subtler detail in her profile].',
    principle: 'SPECIFICITY',
    citation: 'Speed-dating follow-up research',
    contexts: ['tinder', 'hinge'],
    why: 'Skips the crowded question and proves a closer read of her profile.',
  },
];

const BANTER: LibraryLine[] = [
  /* ----------------------- BANTER & ESCALATION (15) ------------------------ */
  {
    id: 'bn-01',
    category: 'banter',
    tone: 'playful',
    stage: 'rapport',
    text: 'Trade you: your most unpopular food opinion for mine. Fair warning, mine ends friendships.',
    principle: 'SELF-DISCLOSURE',
    citation: 'Aron et al., 1997',
    contexts: ['imessage', 'tinder'],
    why: 'A reciprocal trade of small secrets starts the disclosure ladder.',
  },
  {
    id: 'bn-02',
    category: 'banter',
    tone: 'charming',
    stage: 'rapport',
    text: 'What’s something small that makes your whole day better? Collecting data for purely scientific reasons.',
    principle: 'RESPONSIVENESS',
    citation: 'Birnbaum & Reis',
    contexts: ['imessage'],
    why: 'Invites her to share a joy — and tells her you plan to remember it.',
  },
  {
    id: 'bn-03',
    category: 'banter',
    tone: 'playful',
    stage: 'rapport',
    text: 'You’ve mentioned [interest] twice now. Starting to think it’s not a phase. I need the origin story.',
    principle: 'THE CALLBACK',
    contexts: ['imessage', 'hinge'],
    why: 'Shows you track what she says — total attention is the flex.',
  },
  {
    id: 'bn-04',
    category: 'banter',
    tone: 'direct',
    stage: 'building',
    text: 'Settle a debate I’m losing with a friend: best taco in the city — your verdict is final.',
    principle: 'BEN FRANKLIN EFFECT',
    citation: 'Jecker & Landy, 1969',
    contexts: ['imessage'],
    why: 'Asking a small favor makes people like you more — and seeds a venue.',
  },
  {
    id: 'bn-05',
    category: 'banter',
    tone: 'playful',
    stage: 'building',
    text: 'There’s a night market Thursday. I fully intend to get lost in it. Recruiting one accomplice.',
    principle: 'NOVELTY',
    citation: 'Aron et al. — self-expansion',
    contexts: ['imessage'],
    why: 'Novel shared experiences accelerate closeness; “accomplice” frames it as play.',
  },
  {
    id: 'bn-06',
    category: 'banter',
    tone: 'charming',
    stage: 'rapport',
    text: 'Serious question between the jokes: what do you actually want more of this year?',
    principle: 'SELF-DISCLOSURE',
    citation: 'Aron et al., 1997',
    contexts: ['imessage'],
    why: 'Climbs one rung deeper on the disclosure ladder without getting heavy.',
  },
  {
    id: 'bn-07',
    category: 'banter',
    tone: 'playful',
    stage: 'building',
    text: 'We’re at the point where I need your controversial take. One only. Make it count.',
    principle: 'PLAYFULNESS',
    citation: 'Hall, 2015',
    contexts: ['imessage', 'tinder'],
    why: 'Manufactures playful tension — the fuel of escalation — on a safe topic.',
  },
  {
    id: 'bn-08',
    category: 'banter',
    tone: 'charming',
    stage: 'building',
    text: 'Passed a [place tied to her interest] today and had an idea for a very good [activity]. Details available upon interest.',
    principle: 'NOVELTY',
    citation: 'Aron et al. — self-expansion',
    contexts: ['imessage'],
    why: 'Seeds a date as an invitation she can pick up, not a demand she must answer.',
  },
  {
    id: 'bn-09',
    category: 'banter',
    tone: 'direct',
    stage: 'building',
    text: 'Honest check-in: I enjoy talking to you. Does [day] work for doing that over drinks?',
    principle: 'KNOWN LIKING',
    contexts: ['imessage'],
    why: 'States interest plainly and attaches a concrete, low-pressure next step.',
  },
  {
    id: 'bn-10',
    category: 'banter',
    tone: 'playful',
    stage: 'rapport',
    text: 'New game: recommend me one song and I’ll recommend you one. Judging is silent but absolute.',
    principle: 'RECIPROCITY',
    contexts: ['imessage'],
    why: 'Equal exchange builds rhythm; taste-swaps reveal personality fast.',
  },
  {
    id: 'bn-11',
    category: 'banter',
    tone: 'charming',
    stage: 'rapport',
    text: 'What’s the thing you nerd out about that surprises people? I’ll trade you mine after — it’s only fair.',
    principle: 'SELF-DISCLOSURE',
    citation: 'Aron et al., 1997',
    contexts: ['imessage'],
    why: 'Promised reciprocity makes deeper sharing feel safe and mutual.',
  },
  {
    id: 'bn-12',
    category: 'banter',
    tone: 'playful',
    stage: 'building',
    text: 'Your [story content] raises questions. Local legend or happy accident?',
    principle: 'PLAYFULNESS',
    citation: 'Hall, 2015',
    contexts: ['instagram'],
    why: 'A story-reply that continues an existing thread instead of starting cold.',
  },
  {
    id: 'bn-13',
    category: 'banter',
    tone: 'direct',
    stage: 'building',
    text: 'Help me win a small argument: is [light question] genius or madness? You seem like a fair judge.',
    principle: 'BEN FRANKLIN EFFECT',
    citation: 'Jecker & Landy, 1969',
    contexts: ['imessage'],
    why: 'The favor-ask flatters her judgment and pulls her into your world.',
  },
  {
    id: 'bn-14',
    category: 'banter',
    tone: 'charming',
    stage: 'rapport',
    text: 'Tell me something you liked about today. Even tiny. Especially tiny.',
    principle: 'RESPONSIVENESS',
    citation: 'Birnbaum & Reis',
    contexts: ['imessage'],
    why: 'A responsive question about her inner life, wrapped in warmth.',
  },
  {
    id: 'bn-15',
    category: 'banter',
    tone: 'playful',
    stage: 'building',
    text: 'Hypothesis: our banter survives real life. Method: [activity]. Care to run the experiment?',
    principle: 'PLAYFULNESS',
    citation: 'Hall, 2015',
    contexts: ['imessage'],
    why: 'An adventure-frame date seed — playful framing, easy opt-in.',
  },
];

const DATE_ASKS: LibraryLine[] = [
  /* ---------------------------- DATE ASKS (10) ----------------------------- */
  {
    id: 'da-01',
    category: 'date-ask',
    tone: 'direct',
    stage: 'ask',
    text: 'This is too good for an app. Thursday, [specific activity tied to shared interest], 8pm. If the week’s chaos, name your day.',
    principle: 'MOMENTUM — THE CONCRETE ASK',
    contexts: ['imessage', 'tinder'],
    why: 'Concrete plans convert; the open alternate keeps it pressure-free.',
  },
  {
    id: 'da-02',
    category: 'date-ask',
    tone: 'charming',
    stage: 'ask',
    text: 'I’d like to take you to [specific place tied to something she mentioned]. Low stakes, good [coffee / cocktails]. Interested?',
    principle: 'THE CALLBACK',
    contexts: ['imessage'],
    why: 'Ties the plan to her own words — attention made tangible.',
  },
  {
    id: 'da-03',
    category: 'date-ask',
    tone: 'playful',
    stage: 'ask',
    text: 'Proposal: we settle the [ongoing joke debate] in person over [drinks / tacos]. Loser buys round one.',
    principle: 'PLAYFULNESS',
    citation: 'Hall, 2015',
    contexts: ['imessage'],
    why: 'Converts running banter into a date with a built-in reason to meet.',
  },
  {
    id: 'da-04',
    category: 'date-ask',
    tone: 'direct',
    stage: 'ask',
    text: 'I’m free [day] and [day]. One hour, [specific spot], no pressure past that. Which works?',
    principle: 'TIME-BOXED, LOW PRESSURE',
    contexts: ['imessage'],
    why: 'Specific options plus an explicit out respects her autonomy and time.',
  },
  {
    id: 'da-05',
    category: 'date-ask',
    tone: 'charming',
    stage: 'ask',
    text: 'Rather than let this thread become pen pals: [activity] this week? Promise of good conversation — and zero guilt if the schedule’s packed.',
    principle: 'MOMENTUM',
    contexts: ['hinge', 'imessage'],
    why: 'Names the drift everyone fears and offers a graceful out up front.',
  },
  {
    id: 'da-06',
    category: 'date-ask',
    tone: 'playful',
    stage: 'ask',
    text: 'Daytime edition: [market / museum / walk] Saturday morning. Coffee in hand, zero pressure, high snack potential.',
    principle: 'NOVELTY',
    citation: 'Aron et al. — self-expansion',
    contexts: ['imessage'],
    why: 'A daytime ask feels safer and easier to say yes to than a late-night one.',
  },
  {
    id: 'da-07',
    category: 'date-ask',
    tone: 'direct',
    stage: 'ask',
    text: 'We’ve circled this long enough — I’d love to meet. [Specific plan], [day]. If not this week, totally fine.',
    principle: 'MOMENTUM',
    contexts: ['instagram', 'imessage'],
    why: 'Confident and clean: a real plan, a real day, and a real exit ramp.',
  },
  {
    id: 'da-08',
    category: 'date-ask',
    tone: 'charming',
    stage: 'ask',
    text: 'You mentioned loving [cuisine / activity]. I know a place. Come judge whether my taste holds up.',
    principle: 'SPECIFICITY',
    contexts: ['imessage'],
    why: 'The plan is built from her stated taste — the ask itself proves listening.',
  },
  {
    id: 'da-09',
    category: 'date-ask',
    tone: 'playful',
    stage: 'ask',
    text: 'Adventure incoming: [activity], [day]. It’s happening with or without you — it’s just measurably better with.',
    principle: 'NOVELTY',
    citation: 'Aron et al. — self-expansion',
    contexts: ['imessage'],
    why: 'The adventure frame invites without needing — abundance, not pressure.',
  },
  {
    id: 'da-10',
    category: 'date-ask',
    tone: 'direct',
    stage: 'ask',
    text: 'Simple ask: drinks, [day], [neighborhood spot]. One drink minimum, great stories likely. Yes or rain check — both fine.',
    principle: 'TIME-BOXED, LOW PRESSURE',
    contexts: ['imessage'],
    why: 'Clear activity, clear day, and “rain check” normalizes a no.',
  },
];

const EXITS_AND_REVIVALS: LibraryLine[] = [
  /* ------------------------ EXITS & REVIVALS (8) --------------------------- */
  {
    id: 'rv-01',
    category: 'revival',
    tone: 'playful',
    stage: 'stalled',
    text: 'I was promised a [callback to her earlier claim] ranking and I intend to collect.',
    principle: 'THE CALLBACK',
    contexts: ['imessage'],
    why: 'One revival swing built on shared history — light, specific, answerable.',
  },
  {
    id: 'rv-02',
    category: 'revival',
    tone: 'charming',
    stage: 'stalled',
    text: 'No agenda — [song / place / meme] just reminded me of our [topic] debate. Hope your week’s treating you well.',
    principle: 'RESPONSIVENESS',
    citation: 'Birnbaum & Reis',
    contexts: ['imessage', 'instagram'],
    why: 'Re-opens the door with warmth and explicitly asks for nothing.',
  },
  {
    id: 'rv-03',
    category: 'revival',
    tone: 'playful',
    stage: 'stalled',
    text: 'Still genuinely curious: [playful callback question]? If life’s busy, no worries — I just had to ask once.',
    principle: 'GRACE',
    contexts: ['imessage'],
    why: 'A single light question with the out stated plainly — respect shown, not performed.',
  },
  {
    id: 'rv-04',
    category: 'revival',
    tone: 'direct',
    stage: 'stalled',
    text: 'Genuine question, no strings: still up for [the plan you discussed]? If life’s busy, all good — just checking once.',
    principle: 'MOMENTUM',
    contexts: ['imessage'],
    why: 'A single direct check-in with an explicit, sincere out.',
  },
  {
    id: 'ex-01',
    category: 'exit',
    tone: 'charming',
    stage: 'stalled',
    text: 'Seems like life’s busy — no worries at all. You were fun to talk to. Good luck out there.',
    principle: 'GRACE',
    contexts: ['imessage', 'tinder', 'hinge'],
    why: 'Warm, final, door open. Dignity intact on both sides.',
  },
  {
    id: 'ex-02',
    category: 'exit',
    tone: 'direct',
    stage: 'stalled',
    text: 'Timing’s a funny thing. Really enjoyed our chats — if you ever want to pick it back up, the door’s open on my side.',
    principle: 'GRACE',
    contexts: ['imessage'],
    why: 'Warm, final, door open — no guilt, no grievance, dignity on both sides.',
  },
  {
    id: 'ex-03',
    category: 'exit',
    tone: 'charming',
    stage: 'stalled',
    text: 'Taking the hint with good humor: you’re clearly swamped. Wishing you a great [project / season she mentioned].',
    principle: 'GRACE',
    contexts: ['imessage', 'instagram'],
    why: 'The callback makes the goodbye personal instead of a form letter.',
  },
  {
    id: 'ex-04',
    category: 'exit',
    tone: 'direct',
    stage: 'stalled',
    text: 'No hard feelings if this has run its course. Thanks for the laughs — genuinely.',
    principle: 'GRACE',
    contexts: ['tinder', 'hinge', 'imessage'],
    why: 'Gratitude without grievance — the exit that sometimes reopens itself.',
  },
];

export const LINES: LibraryLine[] = [...OPENERS, ...BANTER, ...DATE_ASKS, ...EXITS_AND_REVIVALS];

export function linesByCategory(category: LineCategory): LibraryLine[] {
  return LINES.filter((l) => l.category === category);
}

export function linesByTone(tone: Tone): LibraryLine[] {
  return LINES.filter((l) => l.tone === tone);
}

export function linesByStage(stage: ConversationStage): LibraryLine[] {
  return LINES.filter((l) => l.stage === stage);
}
